services:
  webapi:
      build:
        context: ./..
        dockerfile: api/WebApi/Dockerfile
      container_name: distrib-webapi
      ports:
        - "5000:80"  # Exponer el puerto 5000 en el host
      environment:
        ASPNETCORE_ENVIRONMENT: "Production"  # Puedes cambiar a "Production" si lo deseas
      networks:
        - distrib-network
      depends_on:
        - distrib-sql
        - distrib-rabbit
        - distrib-mongo
        - distrib-redis
  distrib-sql:
    image: mcr.microsoft.com/mssql/server
    hostname: distrib-server-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "!1PasswordBackEnd."
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - distrib-network


  distrib-rabbit:
    image: rabbitmq:3-management
    hostname: distrib-server-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - distrib-network
    volumes:
      - ./tools/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  distrib-mongo:
    image: mongo:6.0
    hostname: distrib-server-mongo
    container_name: distrib-mongo
    ports:
      - "27017:27017"
    networks:
      - distrib-network
    volumes:
      - ./tools/mongo:/data/db

  distrib-redis:
    image: redis:7.0-alpine
    hostname: distrib-server-redis
    container_name: distrib-redis
    ports:
      - "6379:6379"
    networks:
      - distrib-network

networks:
  distrib-network:
    internal: true
    external: true
