apiVersion: v1
kind: Namespace
metadata:
  name: reservar-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: reservar-sql
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-sql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-sql
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-sql
  template:
    metadata:
      labels:
        app: reservar-sql
    spec:
      containers:
        - name: reservar-sql
          image: mcr.microsoft.com/mssql/server
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "!1PasswordBackEnd."
            - name: MSSQL_PID
              value: "Developer"
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: reservar-rabbit
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-rabbit
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-rabbit
  template:
    metadata:
      labels:
        app: reservar-rabbit
    spec:
      containers:
        - name: reservar-rabbit
          image: rabbitmq:3.8.34-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /etc/rabbitmq/rabbitmq.conf
              name: rabbitmq-config
              subPath: rabbitmq.conf
            - mountPath: /etc/rabbitmq/definitions.json
              name: rabbitmq-config
              subPath: definitions.json
            - mountPath: /etc/rabbitmq/enabled_plugins
              name: rabbitmq-config
              subPath: enabled_plugins
      volumes:
        - name: rabbitmq-config
          hostPath:
            path: /path/to/tools/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: reservar-front
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-front
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-front
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-front
  template:
    metadata:
      labels:
        app: reservar-front
    spec:
      containers:
        - name: reservar-front
          image: fabianrzs/reservar-frontend:latest
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: reservar-gateway
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-gateway
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-gateway
  template:
    metadata:
      labels:
        app: reservar-gateway
    spec:
      containers:
        - name: reservar-gateway
          image: fabianrzs/reservar-apigateway:latest
          ports:
            - containerPort: 80
          env:
            - name: RESERVAR_BACKEND_URL
              value: "http://reservar-booking:80"
---
apiVersion: v1
kind: Service
metadata:
  name: reservar-booking
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-booking
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-booking
  template:
    metadata:
      labels:
        app: reservar-booking
    spec:
      containers:
        - name: reservar-booking
          image: fabianrzs/reservar-booking:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reservar-authentication
  namespace: reservar-namespace
spec:
  selector:
    app: reservar-authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservar-authentication
  namespace: reservar-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservar-authentication
  template:
    metadata:
      labels:
        app: reservar-authentication
    spec:
      containers:
        - name: reservar-authentication
          image: fabianrzs/reservar-authentication:latest
          ports:
            - containerPort: 80
